# src/preprocess.py
# ─────────────────────────────────────────────────────────────
# Data Cleaning & Preprocessing Module
# ─────────────────────────────────────────────────────────────
# Handles TWO data sources:
#   1. UCI Household Electric Power Consumption (real dataset)
#   2. Synthetic CSV generated by generate_data.py
# ─────────────────────────────────────────────────────────────

import pandas as pd
import numpy as np
import os

# ── Paths ────────────────────────────────────────────────────
UCI_PATH       = "data/raw/household_power_consumption.txt"
SYNTHETIC_PATH = "data/raw/synthetic_power.csv"
CLEAN_OUT      = "data/processed/clean_data.csv"


def load_uci(filepath: str) -> pd.DataFrame:
    """
    Load the UCI Household Electric Power Consumption dataset.

    Dataset columns (semicolon-separated):
        Date, Time, Global_active_power, Global_reactive_power,
        Voltage, Global_intensity, Sub_metering_1, Sub_metering_2,
        Sub_metering_3

    Missing values are encoded as '?' in the original file.
    We parse Date+Time into a single datetime index and resample
    to hourly averages.
    """
    print("  Loading UCI dataset …")
    df = pd.read_csv(
        filepath,
        sep=";",
        parse_dates={"datetime": ["Date", "Time"]},
        dayfirst=True,          # UCI uses DD/MM/YYYY
        low_memory=False,
        na_values=["?"],
    )
    df.set_index("datetime", inplace=True)
    df = df[["Global_active_power"]].copy()
    df.columns = ["power_kw"]
    df["power_kw"] = pd.to_numeric(df["power_kw"], errors="coerce")
    return df


def load_synthetic(filepath: str) -> pd.DataFrame:
    """Load the pre-generated synthetic CSV (already hourly)."""
    print("  Loading synthetic dataset …")
    df = pd.read_csv(filepath, index_col="datetime", parse_dates=True)
    df.columns = ["power_kw"]
    return df


def clean(df: pd.DataFrame) -> pd.DataFrame:
    """
    Clean a raw power DataFrame:
      1. Forward-fill missing values (≤ 6 consecutive gaps)
      2. Resample to 1-hour mean (idempotent if already hourly)
      3. Remove outliers beyond ±3 standard deviations
      4. Drop any remaining NaN rows
    Returns the cleaned DataFrame.
    """
    # Forward-fill short gaps (realistic for sensor dropouts)
    df = df.copy()
    df["power_kw"] = df["power_kw"].ffill(limit=6)

    # Resample to hourly mean (handles minute-level UCI data)
    df = df.resample("1h").mean()

    # Remove statistical outliers
    mu    = df["power_kw"].mean()
    sigma = df["power_kw"].std()
    mask  = (df["power_kw"] >= mu - 3 * sigma) & (df["power_kw"] <= mu + 3 * sigma)
    before = len(df)
    df    = df[mask].dropna()

    print(f"  After cleaning: {len(df):,} rows  |  "
          f"removed {before - len(df)} outlier/NaN rows  |  "
          f"range [{df['power_kw'].min():.3f}, {df['power_kw'].max():.3f}] kWh")
    return df


def load_and_clean(uci_path: str = UCI_PATH,
                   synthetic_path: str = SYNTHETIC_PATH) -> pd.DataFrame:
    """
    Auto-detect which dataset is available and return a cleaned hourly
    DataFrame.  UCI is preferred; synthetic is used as fallback.
    """
    print("\n[1] PREPROCESSING")
    if os.path.exists(uci_path):
        df = load_uci(uci_path)
    elif os.path.exists(synthetic_path):
        df = load_synthetic(synthetic_path)
    else:
        raise FileNotFoundError(
            "No dataset found.\n"
            "  Option A: Download UCI dataset to data/raw/household_power_consumption.txt\n"
            "  Option B: Run  python -m src.generate_data  to create a synthetic dataset"
        )

    df = clean(df)

    # Persist cleaned data for later inspection / EDA notebook
    os.makedirs("data/processed", exist_ok=True)
    df.to_csv(CLEAN_OUT)
    print(f"  ✓ Saved to {CLEAN_OUT}")
    return df


# ── Quick self-test ───────────────────────────────────────────
if __name__ == "__main__":
    df = load_and_clean()
    print(df.tail())
